CREATE_TEAM_MESSAGE = "## Click to create a team.\n**Note**: You can only create one team. The creator of the team will be the team leader."
JOIN_TEAM_MESSAGE = "## Join a team below.\n**Note**: You can only join one team. If a team leader joins a team other than theirs, their previous team will be deleted."
NEW_TEAM_NAME_PREFIX = "Team-"
DEFAULT_TEAM_CREATE_EMOJI = "✅"
TEAM_LEADER_ROLE_NAME = "Team Leader"
NO_TEAM_OPTION = "Teamless"
NO_TEAM_EMOJI = "❌"
TEAM_NAME_MAX_LENGTH = 24
FROZEN_TEAM_TEXT = "The team formation process has ended. Please contact a staff member to edit your team status."
RECOMMENDED_TEAM_SIZE = 4
DEFAULT_TEAM_EMOJI = "👥"
EMOJI_SEPARATOR = "┊"
